name: release

on:
  push:
    branches:
      - 'release/*'

jobs:
  get_version:
    name: Get release version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Get release version
        id: get_version
        uses: battila7/get-version-action@v2

  release:
    name: Build ${{ github.ref }}
    runs-on: ubuntu-latest
    needs: get_version
    outputs:
      url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create changelog
        id: create_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: true
          stripHeaders: true

      - name: Change version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: v${{ needs.get_version.outputs.version }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.get_version.outputs.version }}
          release_name: v${{ needs.get_version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ steps.create_changelog.outputs.changelog }}

  build:
    name: Build image and push to Docker HUB
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    needs: get_version

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jazflix-api:${{ needs.get_version.outputs.version }}
